### ISSUE TITLE
Define a new governance for the project

### ISSUE THREAD

**Issue by hfiguiere** [photo/frontend#1584]
Now that Trovebox is no more, this promising open source project needs a new governance. ie formal maintainer(s) to get contributions in.

**Comment by hfiguiere** [comment]
officially pinging @jmathai

**Comment by jmathai** [comment]
@hfiguiere I started gh-1570 for this purpose. Would love to figure out how to hand over the reigns.

Something I think needs to happen is to clean it up so that it is easy to reproduce a working version of the software. Something that's languished over time. It's something I should be able to set up.

Could you post your ideas over at the other thread?
